name: curl action
description: test action

inputs:
  version:
    description: 'Version of the mod file'
    required: false
  changelog:
    description: 'Changelog of the mod file'
    required: false
  changelog-path:
    description: 'Path to changelog of the mod file'
    required: false
  active:
    description: 'Label this upload as the current release (Default: true)'
    required: false
    default: 'true'
  filehash:
    description: 'Filehash of the mod file'
    required: false
  metadata:
    description: 'Metadata blob of the mod file'
    required: false
  metadata-path:
    description: 'Path to the metadata blob of the mod file'
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        curl_version=$(curl -V | head -1 | cut -d ' ' -f2)

        if dpkg --compare-versions "$curl_version" lt "7.76.0"; then
          echo '::notice ::curl 7.76+ is required. Installing curl from snap.'
          sudo snap install curl
          echo '/snap/bin' >> $GITHUB_PATH
        fi
    - id: form
      shell: bash
      env:
        version: ${{ inputs.version }}
        changelog: ${{ inputs.changelog }}
        changelog_path: ${{ inputs.changelog-path }}
        active: ${{ inputs.active }}
        filehash: ${{ inputs.filehash }}
        metadata: ${{ inputs.metadata }}
        metadata_path: ${{ inputs.metadata-path }}
      run: |
        # env
        curl_fields=()

        if [ -n "$version" ]; then
            file=$(mktemp -p $RUNNER_TEMP version.XXXX)
            echo -n $version > $file
            curl_fields+=("'version=<$file'")
        fi

        if [ -n "$changelog" ]; then
            file=$(mktemp -p $RUNNER_TEMP changelog.XXXX)
            echo -n $changelog > $file
            curl_fields+=("'changelog=<$file'")
        elif [ -f "$changelog_path" ]; then
            curl_fields+=("'changelog=<$changelog_path'")
        fi

        if [ "$active" = "true" ]; then
            curl_fields+=("'active=true'")
        elif [ "$active" = "false" ]; then
            curl_fields+=("'active=false'")
        fi

        if [ -n "$filehash" ]; then
            file=$(mktemp -p $RUNNER_TEMP filehash.XXXX)
            echo -n $filehash > $file
            curl_fields+=("'filehash=<$file'")
        fi

        if [ -n "$metadata" ]; then
            file=$(mktemp -p $RUNNER_TEMP metadata.XXXX)
            echo -n $metadata > $file
            curl_fields+=("'metadata_blob=<$file'")
        elif [ -f "$metadata_path" ]; then
            curl_fields+=("'metadata_blob=<$metadata_path'")
        fi

        echo ${curl_fields[@]}
        echo "fields=$(for i in ${!curl_fields[@]}; do echo -n ' -F' ${curl_fields[$i]}; done)" >> $GITHUB_OUTPUT

        cat $GITHUB_OUTPUT

    - run: curl --fail-with-body https://httpbin.org/post ${{ steps.form.outputs.fields }}
      if: steps.form.outputs.fields
      shell: bash
