name: curl action
description: test action

inputs:
  version:
    description: 'Version of the mod file'
    required: false
  changelog:
    description: 'Changelog of the mod file'
    required: false
  changelog-path:
    description: 'Path to changelog of the mod file'
    required: false
  active:
    description: 'Label this upload as the current release (Default: true)'
    required: false
    default: 'true'
  filehash:
    description: 'Filehash of the mod file'
    required: false
  metadata:
    description: 'Metadata blob of the mod file'
    required: false
  metadata-path:
    description: 'Path to the metadata blob of the mod file'
    required: false

runs:
  using: composite
  steps:
    - id: form
      shell: bash
      run: |
        curl_fields=()

        if [ -n "$INPUT_VERSION" ]; then
            curl_fields+=("\"version=$INPUT_VERSION\"")
        fi

        if [ -n "$INPUT_CHANGELOG" ]; then
            curl_fields+=("\"changelog=$INPUT_CHANGELOG\"")
        elif [ -f "$INPUT_CHANGELOG_PATH" ]; then
            curl_fields+=("\"changelog=<$INPUT_CHANGELOG_PATH\"")
        fi

        if [ "$INPUT_ACTIVE" = "true" ]; then
            curl_fields+=('"active=true"')
        elif [ "$INPUT_ACTIVE" = "false" ]; then
            curl_fields+=('"active=false"')
        fi

        if [ -n "$INPUT_FILEHASH" ]; then
            curl_fields+=("\"filehash=$INPUT_FILEHASH\"")
        fi

        if [ -n "$INPUT_METADATA" ]; then
            curl_fields+=("\"metadata_blob=$INPUT_METADATA\"")
        elif [ -f "$INPUT_METADATA_PATH" ]; then
            curl_fields+=("\"metadata_blob=<$INPUT_METADATA_PATH\"")
        fi

        echo "fields=$(for f in ${curl_fields[@]}; do echo -n ' -F' $f; done)" >> $GITHUB_OUTPUT

        cat $GITHUB_OUTPUT

    - run: curl https://httpbin.org/post ${{ steps.form.outputs.fields }}
      shell: bash
