name: clippy

on: workflow_dispatch

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: beta
          components: clippy

      - run: cargo clippy
