name: Composite Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.14
          - macos-10.15
          - macos-11.0
          - windows-2016
          - windows-2019

    steps:
      - run: |
          python -V || true
          python3 -V || true
      - uses: actions/checkout@v2
      - uses: ./.github/actions/toolchain
        with:
          components: rustfmt,clippy
