name: curl

on: [push, pull_request]

jobs:
  curl:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
          os: [ubuntu-latest, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/curl-action
        with:
          version: "1.0"
          changelog: "asdasdf \" asdf"
