name: matrix-on-nightly

on: push

jobs:
  test:
    name: Fail on nightly
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - stable
          - nightly

    steps:
      - run: echo ${{ matrix.rust }}
      - run: exit 1
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        if: matrix.rust == 'nightly'
