name: install-action

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-deny@0.13.4
      - uses: Swatinem/rust-cache@v2.2.0

      - run: cargo deny --log-level debug --manifest-path cargo-deny-test/Cargo.toml list
