name: install-action

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - uses: taiki-e/install-action@v1
      #   with:
      #     tool: cargo-deny@0.13.4

      - run: env
      - uses: nickelc/cargo-deny-action@composite-action
        with:
          log-level: debug
          command: list

      - run: cargo deny --version
