name: install-action

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-deny@0.13.4

      - run: cargo deny --version
