name: jq

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - uses: numworks/setup-msys2@v1
      - run: msys2do uname -a
      - run: msys2do pacman --noconfirm -S automake autoconf
      - run: msys2do pacman --noconfirm -S base-devel
      - run: msys2do pacman --noconfirm -S mingw-w64-x86_64-toolchain
      - run: msys2do pacman --noconfirm -S mingw-w64-x86_64-rust
      - run: msys2do pacman -Ql automake autoconf
      - run: msys2do cargo build
