name: macOS test

on: [push, pull_request]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - run: brew install tree

      - name: Install toolchain
        id: tc
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-test1-${{ steps.tc.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.toml') }}

      - run: tree -ugp target

      - name: Build all features
        run: cargo build --all-features

      - run: tree -ugp target
