name: Upload to modio

on:
  push:
    tags:
      - '*'

jobs:
  upload:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Mod
        uses: actions/checkout@v3
        with:
          repository: VorTechnix/Aground-Notebook
          path: notebook
      - name: Package
        id: package
        run: |
          name="notebook"
          tag=$(git describe --tags --abbrev=0)
          filename="$name-$tag.zip"
          cd notebook
          zip "../$filename" *

          echo "modfile=$filename" >> $GITHUB_OUTPUT
          echo "version=$tag" >> $GITHUB_OUTPUT

      - uses: nickelc/upload-to-modio@v1.0.9
        id: upload
        with:
          test-env: true
          token: ${{ secrets.MODIO_TOKEN }}
          game: 206
          mod: 1041
          version: ${{ steps.package.outputs.version }}
          path: ${{ steps.package.outputs.modfile }}

      - name: Test outputs
        run: |
          echo "id: ${{ steps.upload.outputs.id }}"
          echo "url: ${{ steps.upload.outputs.url }}"
